server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    add_header Cache-Control "no-store" always;

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }

    location ~* \.(mp4|webm|jpe?g|png|woff2?)$ {
        add_header Cache-Control "public, max-age=3600" always;
    }

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
}
